### PR TITLE
Add support for selecting a camera by deviceId

### LINKED ISSUE #34: Choose specific camera
In apps like Google Meet I can specifically choose a camera by name on my PC.

When I use this library, I can't choose the camera.  I can't even change cameras using the video camera selection in the navigation bar.

Any idea whether it's possible to show the user a list of video inputs and let them choose the one they want?

### PR DESCRIPTION
**Pull request by dobesv**
fixes https://github.com/MABelanger/jslib-html5-camera-photo/issues/34

### CODE REVIEW

**Comment by Aarbel** [comment]
@MABelanger why did you closed this PR ? 
What is the best way to select a specific deviceId ?

**Comment by Aarbel** [comment]
@dobesv have you found a way to solve your problem ?

**Comment by dobesv** [comment]
We use yarn's `patch` system to update this package just for our project.  As for why the PR was closed, no idea.

**Comment by Aarbel** [comment]
@dobesv thanks a lot, what is your yarn patch command to include all of your changes ?

**Comment by Aarbel** [comment]
> @dobesv thanks a lot, what is your yarn patch command to include all of your changes ?

@dobesv following back,

Thanks a lot for your tips ;)

**Comment by dobesv** [comment]
> @dobesv thanks a lot, what is your yarn patch command to include all of your changes ?

Hi, it's a bit complicated, you'll have to look at the docs and figure it out.

**Comment by dearsina** [comment]
Can we please reopen this thread and commit this pull request? @dobesv seems to have solved the problem, or am I missing something?

**Comment by MABelanger** [comment]
Hello,
Sorry for late reply, thank for the suggestion and the PR. I decided to use cameraDevice as the first parameter instead of adding a third of deviceId. we can now select a camera with the deviceId, check the API : 
image

Thank,
@dearsina  and @dobesv

**Comment by MABelanger** [comment]
@dobesv 
Thank for your PR i realy appreciated. Your PR was closed on a batch close with other PR of the robot, sorry about it. I will look to the other PR on react-html5-camera-photo side.

**Pull request closed without merging**
